name: Build Handouts
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            IntroDataScience/Slides-IntroDataScience.tex
            IntroPythonJupyter/Slides-IntroPythonJupyter.tex
            AIMethods/Slides-AIMethods.tex
            WebApp/Slides-WebApp.tex
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: |
             IntroDataScience/Slides-IntroDataScience.pdf
             IntroPythonJupyter/Slides-IntroPythonJupyter.pdf
             AIMethods/Slides-AIMethods.pdf
             WebApp/Slides-WebApp.pdf
